Fix some families sharing same stage for sorting purposes. (#3)
* Fix some families sharing same stage for sorting purposes.

Error: Family 18 has members sharing the same stage 3:
  - Vileplume
  - Bellossom
Error: Family 22 has members sharing the same stage 2:
  - Persian
  - Perrserker
Error: Family 26 has members sharing the same stage 3:
  - Poliwrath
  - Politoed
Error: Family 33 has members sharing the same stage 2:
  - Slowbro
  - Slowking
Error: Family 47 has members sharing the same stage 2:
  - Hitmonlee
  - Hitmonchan
  - Hitmontop
Error: Family 58 has members sharing the same stage 2:
  - Scizor
  - Kleavor
Error: Family 67 has members sharing the same stage 2:
  - Vaporeon
  - Jolteon
  - Flareon
  - Espeon
  - Umbreon
  - Leafeon
  - Glaceon
  - Sylveon
Error: Family 96 has members sharing the same stage 2:
  - Quagsire
  - Clodsire
Error: Family 109 has members sharing the same stage 2:
  - Weavile
  - Sneasler
Error: Family 135 has members sharing the same stage 2:
  - Silcoon
  - Cascoon
Error: Family 135 has members sharing the same stage 3:
  - Beautifly
  - Dustox
Error: Family 140 has members sharing the same stage 3:
  - Gardevoir
  - Gallade
Error: Family 144 has members sharing the same stage 2:
  - Ninjask
  - Shedinja
Error: Family 186 has members sharing the same stage 2:
  - Glalie
  - Froslass
Error: Family 188 has members sharing the same stage 2:
  - Huntail
  - Gorebyss
Error: Family 213 has members sharing the same stage 2:
  - Wormadam
  - Mothim
Error: Family 287 has members sharing the same stage 2:
  - Cofagrigus
  - Runerigus
Error: Family 413 has members sharing the same stage 3:
  - Solgaleo
  - Lunala
Error: Family 441 has members sharing the same stage 2:
  - Flapple
  - Appletun
Error: Family 489 has members sharing the same stage 2:
  - Armarouge
  - Ceruledge

These are the ones I knew about but didnt touch either because I believe it is correct/intended or I didnt have enough knowledge about the pokemon to be sure how to fix.

* Shift baby classification down to 0, fix manaphy/phione

---------

Co-authored-by: David Yang <davidyang6us@gmail.com>